### ISSUE TITLE
Playback without JavaScript

### ISSUE THREAD

**Issue by aef** [klemens/ff-youtube-all-html5#45]
Would it be anyhow possible to play YouTube videos without the need to enable JavaScript in NoScript? Direct media playback, for example in case of WebM files can be done without it. I guess it will be more complex than this.

**Comment by klemens** [comment]
I'm sorry, this will not happen, because even if it is possible now by getting the direct url to the video, in the future with mse becoming standard, js will be required.
Aside from that I don't see any reason why you wouldn't allow js on youtube.

**Comment by aef** [comment]
JavaScript has been used to deanonymize people in case of using Tor and Tor Browser, therefore they generally recommend to disable it if possible. For video, so far, that has never been an option before HTML5 video. It genereally interested me, if it would be possible at all.

**Comment by klemens** [comment]
Ok, fair point.
Like it said, currently this seems to be possible, because the videos exist as complete files and are accessible directly through their urls. There are already some youtube desktop players (especially under linux) and download tools that seem to do exactly this.
The problem with implementing this here is that the addon itself is written in js and injects js into the page to interact with it. It especially depends on the youtube player code.
The other problem is, like in mentioned already, that youtube is switching to mse with adaptive streaming and so it will no longer be possible to directly download a video. You would have to reimplement the mse code the youtube player uses (and update it every time youtube changes something) which is not something I am keen to do.

**Comment by aef** [comment]
Thanks for the details.
