### ISSUE TITLE
HTML 5 player is not applied in case of full window player URLs

### ISSUE THREAD

**Issue by aef** [klemens/ff-youtube-all-html5#47]
When opening a YouTube video via the full window player URL, your addon doesn't seem to trigger at all. See https://www.youtube.com/v/jNQXAC9IVRw for an example. It would be nice if those would also be replaced by HTML 5 player.

**Comment by klemens** [comment]
Clicking this link just gives me the player swf file. I am not sure that there is an extra full window page which uses html5, because the html5 player uses the html5 fullscreen feature which just displays part of a page in fullscreen.
You could alternatively use the embed url: https://www.youtube.com/embed/jNQXAC9IVRw (this is supported since version 2.2.0beta1)
