### ISSUE TITLE
HTML5 is standard in YouTube

### ISSUE THREAD

**Issue by davidhedlund** [klemens/ff-youtube-all-html5#62]
On the AMO page for your add-on: Can you mention that HTML5 is standard on YouTube so people do not feel that they must install a HTML5 add-on to use it?

**Comment by klemens** [comment]
This is only the case if you are using a recent version of firefox that supports native H264 or VP9 decoding, otherwise youtube will still defaults to using the flash player (IIRC this is the case on windows xp and older linux distrubutions, but I haven't checked recently).

However I wanted to rework the README anyway for the next release (3.1.0), and then I will take a look at the amo descriptions as well.

**Comment by davidhedlund** [comment]
@klemens Thank you.

**Comment by klemens** [comment]
I updated the README and the description of the add-on: de679b14227f7332f32bc18f2c06abc0d854cafb I will update AMO when releasing the final 3.1.0.

**Comment by davidhedlund** [comment]
@klemens Check.

**Comment by klemens** [comment]
Done, version 3.1.0 is currently in the review queue and I just updated the description: https://addons.mozilla.org/firefox/addon/youtube-all-html5/

**Comment by davidhedlund** [comment]
@klemens What did you state on the AMO page (I could not figure it out)?

**Comment by klemens** [comment]
I replaced the description with the one from the README and the short summary is now
> Play all videos on YouTube with your preferred settings (size, quality, playback rate, …) without cookies using only HTML5.

instead of 
> Play all videos on YouTube without Flash in the size and quality you want.

highlighting that the main feature is no longer Flash avoidance.

The description also mentions:
> Force HTML5 in cases when YouTube still defaults to Flash

**Comment by davidhedlund** [comment]
While that is an improvement you didn't state that "HTML5 is standard in YouTube".

**Comment by klemens** [comment]
While I didn't state this explicitly, I think it is pretty obvious. Why would anyone think they need an add-on to use HTML5 on youtube? From today's perspective it is of course a little bit unfortunate that the add-on is called "…ALL HTML5", but that is something that I cannot change anymore.

I also think the new list of features now makes it very clear what to expect. I won't remove any of the Flash-blocking features anytime soon, because I am sure there are still people using it, and so it would be strange to not mention those as a feature.
However, it is planned to set the default of the "video loading method" option to disabled (and remove the already deprecated IE method) in the next release and update the description to mention that this is probably not necessary anymore in most cases, but I don't want to rush this.

**Comment by davidhedlund** [comment]
Ok. Thank you.
