### ISSUE TITLE
TypeError: addonInfo is undefined

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [klemens/ff-youtube-all-html5#65]
I was on my Mozilla submission page ( https://addons.mozilla.org/fr/developers/addons ) and there's this error when I right click on addon titles (that are links).

Also, I have a question, do you plan to move your addon into a Web Extension, on Firefox? I ask because of Firefox 57, I guess you read the information about it.

```
youtube-all-html5:
TypeError: addonInfo is undefined
Trace de la pile :
hasMatchingContext@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:311:11
isItemVisible@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:330:8
setVisibility@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:776:21
updateItemVisibilities@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:1007:7
```

**Comment by klemens** [comment]
Interesting, I also get this error, but it is always preceded by a `TypeError: addonInfo is undefined`, unfortunately without a stacktrace. It also happens eg for links on github.

I am not sure what the problem is, as my [context menu script](https://github.com/klemens/ff-youtube-all-html5/blob/master/data/context-menu.js) is quite straightforward (and working correctly!) and does not access any special properties. It might be a add-on-sdk issue (maybe [1159824](https://bugzilla.mozilla.org/show_bug.cgi?id=1159824), but I am not sure), but it seems these are no longer fixed, as the focus is now completely on web extensions. 😢

If you don't use the context menu feature, you can disable it in the add-on setting.

About porting to a web-ex: The content script part should be no problem, but I am not sure about the other functions which require manipulating cookies and http requests and responses. Also I am not sure if I will stay on firefox at all, given that about half of the extensions I use myself won't be possible as web extensions, as they all manipulate the user interface in some way.

**Comment by ZatsuneNoMokou** [comment]
I understand that, but personally, there will be things that will make me stay on Firefox, I think, and there's still some chances that the api added by Mozilla on the Web Extension makes the job. 
And anyway, with it or now, if you make your addon for Chrome, it will work on Firefox, in which version in the question ^^ (my "main" addon work well, still some bugs but it's not too bad)

**Comment by ZatsuneNoMokou** [comment]
Maybe this error belongs to you too "Error: call to Function() blocked by CSP"' from "resource://gre/modules/commonjs/sdk/system/events.js" and in the Observer

**Comment by klemens** [comment]
Ops, this was the error I meant in my first post, but pasted the wrong line. 😉

I certainly won't port my add-on to chrome or switch to this browser. But there are already active forks of firefox and I guess there will be even more at the end of the year.

**Comment by ZatsuneNoMokou** [comment]
Firefox on Ubuntu still accept unsigned addons, so there's big chances x)

**Comment by ZatsuneNoMokou** [comment]
And well, the main thing I really love is player size change x)
